@baseUrl = http://localhost:3334
@accessToken = {{login.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@gmail.com",
    "password": "12345"
}

###

# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "matheus@gmail.com",
    "password": "12345"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Nova pergunta 2",
    "content": "Conteudo da pergunta 2"
}
###

# @name list_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}